### ISSUE TITLE
Register Email schaut kaputt aus

### ISSUE THREAD

**Issue by bountin** [Hemeroc/reset#1]
Sollte wohl besser aussehen, zB das Logo anzeigen.

<img width="730" alt="screenshot 2015-09-16 01 31 53" src="https://cloud.githubusercontent.com/assets/208063/9892823/d08ba12a-5c12-11e5-992f-63f095c644e0.png">

**Comment by 4nt1m0n** [comment]
Ich habe die Mail von der Adresse satreset@gmx.at erhalten. Eine GMX Adresse finde ich für diesen Zweck nicht sehr schön.

**Comment by mokipedia** [comment]
Should be fixed by now

**Comment by mokipedia** [comment]
@gmx: testmail, production will be no-reply@reset.inso.tuwien.ac.at
