### ISSUE TITLE
Cannot checkout git repository

### ISSUE THREAD

**Issue by matthiasseidemann** [Hemeroc/reset#10]
I tried to check out my git repository for the individual phase using the provided https address and the RESET-Account credentials. I get the following error:
`fatal: remote error: FATAL: R any individual/sepm/2015_WS/0828081 0828081 DENIED by fallthru
(or you mis-spelled the reponame)`

The username and password should be right, because if I change it to something wrong I get a different error `(Authentication failed: ....)`.

**Comment by mokipedia** [comment]
Git is working locally, however this not yet live and therefore the git repo will not be triggered in this first test run.
