### ISSUE TITLE
Cannot submit assignment interview results

### ISSUE THREAD

**Issue by matthiasseidemann** [Hemeroc/reset#11]
I enrolled for the C++/Python assignment with my student account and as a tutor I try to enter the assignment interview results. I enter valid values into the fields and klick on the Save button, but literally nothing happens. I remain on the page and no message appears. And yes, the button changes to active as soon as all fields are filled with values.

Edit: Just fyi I am also registered for a timeslot for the interview.

**Comment by alexeiZamyatin** [comment]
should work now. The problem was that the tutor was not active yet and thus cannot be selected as evaluator. The "me" button / preselect or the currently logged in tutor overrides this (thats the actual bug) and causes the unexpected behavior.
