### ISSUE TITLE
Registrieren nicht möglich mit umlaut im Namen

### ISSUE THREAD

**Issue by Thoma5** [Hemeroc/reset#2]
Ein Klick auf Registrieren führt auf den ZID Login, und nach erfolgter Anmeldung werde ich zurückverwiesen auf https://reset.inso.tuwien.ac.at/#/login.
Stoppe ich den redirect und ersetze in der URL (https://reset.inso.tuwien.ac.at/#/auth?sKey=...&oid=....&mn=...&firstName=Thomas&lastName=M%F6rbauer&title=&mail=...) das %F6 mit einem ö, komme ich für einen Sekundenbruchteil auf die richtige Register Seite, gefolgt von einem weiteren redirect auf die Login Seite mit Error "TU SSO authentication was unsuccessful...".

**Comment by mokipedia** [comment]
könnt halt daran liegen, dass du damit die checksum änderst? ^^

**Comment by Thoma5** [comment]
Das ist schon klar, dass es dann nicht mehr funktioniert wenn ich etwas ändere. Das eigentliche Problem ist, dass %F6 nicht richtig verarbeitet wird. Ein ähnliches Problem gabs 2014SS in BHCI/GSI auf der Aurora Seite.

**Comment by mokipedia** [comment]
Ich teste das lokal mal mit einem Mockup SSO, dann weis ich mehr.

**Comment by konhoe** [comment]
Ich werde nach dem Klick auf Register auch zuerst zum ZID Login und dann auf die Login Seite weitergeleitet. Jeder weitere Klick auf Register führt mich wieder direkt zur Login Page. Habe auch ein Umlaut in meinem Namen (Konstantin Höbart). Soweit ich das seh werd ich zuerst auf https://reset.inso.tuwien.ac.at/#/auth?sKey=...&oid=...&mn=...&firstName=Konstantin&lastName=H%F6bart&title=&mail=... , danach auf https://reset.inso.tuwien.ac.at/#/auth?sKey=...&oid=...&mn=...&firstName=Konstantin&lastName=undefined&title=&mail=... und dann erst auf die Login Page weitergeleitet

**Comment by mokipedia** [comment]
bug confirmed, on it.

**Comment by mokipedia** [comment]
This bug has now been fixed an will be included in the next testrun
