### ISSUE TITLE
Change password does not show error/warning when the current password is wrong

### ISSUE THREAD

**Issue by matthiasseidemann** [Hemeroc/reset#3]
Change password does not show error/warning when the current password is wrong. The Language was set to english.

**Comment by mokipedia** [comment]
Assuming you are logged in?

**Comment by matthiasseidemann** [comment]
Of course I am logged in. I klick on my student number on the right upper corner. Then I enter a new password, repeat the new password, enter a wrong current password and klick on "Update". Then I don't see any error message and remain on the Account Settings page.

Used Firefox 40.0.3 on Windows 10 - 64 Bit.

**Comment by alexeiZamyatin** [comment]
Could not reproduce the described behavior.. However there IS a bug. Looking into it..
