### ISSUE TITLE
Changing the password successfully gives missleading error

### ISSUE THREAD

**Issue by matthiasseidemann** [Hemeroc/reset#4]
Changing the password logs you out (probably intentional) and gives the following error message: Authentication token was either missing or invalid.

I don't think this error message should be shown because it implies that something went wrong, even though that is not true.

**Comment by mokipedia** [comment]
When does the error show up exactly?

**Comment by matthiasseidemann** [comment]
I klick on the account settings. Then I enter a new password twice and the correct current password. I klick on "Update" and I land on the login page showing a error message besides a success message. Then I can login with the new password.

Tested on Firefox 40.0.3 on Windows 10 - 64 Bit.

![change_password](https://cloud.githubusercontent.com/assets/1668082/9906336/006b6f7a-5c8a-11e5-9693-78a4bfa3d272.png)
