### ISSUE TITLE
Password reset entering student number does not have any effect

### ISSUE THREAD

**Issue by matthiasseidemann** [Hemeroc/reset#5]
No matter what you put into the field, the password reset works. Furthermore, the description text there asks for a username instead of a student number.

**Comment by mokipedia** [comment]
Will change to student number. 

Define "works" pls

**Comment by matthiasseidemann** [comment]
I enter any number or string, then I get redirected to the ZID Authentication and if I log in there I get to the page to set a new password for the account related to my student number that I use at the ZID login. It does not mean that the password reset itself doesn't work, but entering the student number when I click on "Forgot password" is just useless from my point of view.

**Comment by mokipedia** [comment]
This is partially correct. From a student perspective, this field is useless.
But students are not the only users.

**Comment by alexeiZamyatin** [comment]
This workflow is intentional.

**Comment by alexeiZamyatin** [comment]
We will however provide an improved UI in the next release.
