### ISSUE TITLE
Git shows up but appears to be broken

### ISSUE THREAD

**Issue by derdritte** [Hemeroc/reset#7]
Role: Student

EDIT:
The git repository does not appear to be valid (the link provided).
Cloning it did not work, no password was required.
Opening the link in a browser resulted in a git-interface (auth required) which did not include the repository specified and defaulted back to the home page.

**Comment by alexeiZamyatin** [comment]
Please provide more details on the reported error. You can use the feedback functionality (however, not on mobile) too, if you feel that this way you can provide a better desription of the error.

**Comment by alexeiZamyatin** [comment]
Btw. the GIT Repo-view ist currently mockup and thus provides no functionality
